### ISSUE TITLE
`vm.stopBroadcast` may now fail if there was no broadcast happening

### ISSUE THREAD

**Issue by KholdStare** [0xPhaze/upgrade-scripts#3]
Hey! Not sure if this affects this library yet, but I think it could in the dry run configuration.

This commit included in the forge nightly build will halt forge if you `vm.stopBroadcast` if it's not already broadcasting: https://github.com/foundry-rs/foundry/pull/4347

Rationale arose from here: https://github.com/foundry-rs/foundry/issues/2453

I feel like this could be affected: https://github.com/0xPhaze/upgrade-scripts/blob/master/src/UpgradeScripts.sol#L317

**Comment by 0xPhaze** [comment]
cool, thanks for reporting. Will look into it.

**Comment by 0xPhaze** [comment]
Should be fixed now

**Comment by KholdStare** [comment]
@0xPhaze Thanks! 👍
