### ISSUE TITLE
Feature request: having a new flag that disable console.log outputs

### ISSUE THREAD

**Issue by 0xGabi** [0xPhaze/upgrade-scripts#5]
While `console.log` is great and appreciated. During testing would be great to be able to turn them off once we are confidence that our proxies are behaving as we expect so we don't clutter the output. Ideally, do something similar to the existing levels of verbosity.

For example:
<img width="845" alt="Screenshot 2023-02-19 at 11 44 16 AM" src="https://user-images.githubusercontent.com/9082013/219955479-7ebccac4-8d5b-4177-9d24-b357664e89d9.png">

Happy to help with this new feature if you found it valuable. Let me know what do you think.

**Comment by 0xGabi** [comment]
I'm closing this after realizing that I was always running my tests with -vvv enable by default 🫠

**Comment by 0xPhaze** [comment]
Haha, yeah, actually had the same happen to me and I realized that I shouldn't be using `-vvv` if I want less output.
